name: online_clearance
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  image_picker: ^1.1.2
  file_picker: ^8.1.4 
  firebase_storage: ^12.3.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  photo_view: ^0.15.0
  video_player: ^2.9.2
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.0.2
  dio: ^5.7.0
  table_calendar: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.6
  shared_preferences: ^2.5.1
  crypto: ^3.0.1
  pdf: ^3.10.4
  printing: ^5.12.0
  csv: ^5.0.2
  open_file: ^3.2.1
  excel: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Tatak_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png" 
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/ndmu.jpg
    - assets/generic_avatar.png
    - assets/logo_ndmu.png
    - assets/tatak_logo.png
    - assets/color.png
    - assets/marian_logo.png

