// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDunCLwkuDA1Ib-aviq9IJKoOPlxZWg984',
    appId: '1:773454718482:web:24802ed2fb59ac3305dacb',
    messagingSenderId: '773454718482',
    projectId: 'tatak-clearance',
    authDomain: 'tatak-clearance.firebaseapp.com',
    storageBucket: 'tatak-clearance.firebasestorage.app',
    measurementId: 'G-YDJ4QS4JNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDumWAsR6z-CTco51jC4Eff5cl8BHbCteo',
    appId: '1:773454718482:android:4ba66fb61fb36e9005dacb',
    messagingSenderId: '773454718482',
    projectId: 'tatak-clearance',
    storageBucket: 'tatak-clearance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQVQ1pd146VhdoX8g4GIPmtO0hdWIqX8o',
    appId: '1:773454718482:ios:473eda4e1637babe05dacb',
    messagingSenderId: '773454718482',
    projectId: 'tatak-clearance',
    storageBucket: 'tatak-clearance.firebasestorage.app',
    iosBundleId: 'com.example.tatak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQVQ1pd146VhdoX8g4GIPmtO0hdWIqX8o',
    appId: '1:773454718482:ios:473eda4e1637babe05dacb',
    messagingSenderId: '773454718482',
    projectId: 'tatak-clearance',
    storageBucket: 'tatak-clearance.firebasestorage.app',
    iosBundleId: 'com.example.tatak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDunCLwkuDA1Ib-aviq9IJKoOPlxZWg984',
    appId: '1:773454718482:web:a49cd76ff5204e3705dacb',
    messagingSenderId: '773454718482',
    projectId: 'tatak-clearance',
    authDomain: 'tatak-clearance.firebaseapp.com',
    storageBucket: 'tatak-clearance.firebasestorage.app',
    measurementId: 'G-N5W1FQ7QS6',
  );
}
